### ISSUE TITLE
[Feature Request] Increase size of transparent outline.

### ISSUE THREAD

**Issue by ShibeTemple** [purogu/itsjustlights#5]
Hi, really like the mod. Love the old-style lights added by Red Power/Project Red. Is there any way that there could be an increase in the size of the transparent outline of the lit blocks? I briefly looked at the texture files and I believe you have the size hardcoded in. Maybe make it a configurable parameter?

**Comment by purogu** [comment]
Hi @ShibeTemple, the width of the outline can be adjusted by altering the model for the lamp via a datapack. The model used when the lamp is on is located at `assets\itsjustlights\models\block\lamp_on.json` Using this datapack: [itsjustlights-datapack.zip](https://github.com/purogu/itsjustlights/files/8136865/itsjustlights-datapack.zip) you can tweak the size of the transparent portion

**Comment by ShibeTemple** [comment]
Thank you!
